<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ExileCore">
      <HintPath>$(exapiPackage)\ExileCore.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ImGui.NET">
      <HintPath>$(exapiPackage)\ImGui.NET.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameOffsets">
      <HintPath>$(exapiPackage)\GameOffsets.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SharpDX">
      <HintPath>$(exapiPackage)\SharpDX.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SharpDX.Mathematics">
      <HintPath>$(exapiPackage)\SharpDX.Mathematics.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
